### ISSUE TITLE
Problem running initscript - LNDK error

### ISSUE THREAD

**Issue by sbddesign** [LN-Zap/bolt12-playground#32]
### Bug Description

I am getting an error regarding LNDK when trying to initialize the project.

What I did:

- Ran `git clone --recursive https://github.com/LN-Zap/bolt12-playground.git`
- Cd'ed into that directory
- Ran `./scripts/init.sh
- Log output looks good until it hits the LNDK part: ` => ERROR [bolt12-playground-lndk2 builder 4/6] RUN git clone https://github.com/orbitalturtle/lndk.git .     && git reset --hard   1.4s
------                                                                                                                                   
 > [bolt12-playground-lndk2 builder 4/6] RUN git clone https://github.com/orbitalturtle/lndk.git .     && git reset --hard b8174e191607406fd335483b892e2bd3693a25de     && cargo build --release:                                                                                 
#0 0.506 Cloning into '.'...                                                                                                             
#0 1.325 fatal: Could not parse object 'b8174e191607406fd335483b892e2bd3693a25de'.                                                       
------
failed to solve: executor failed running [/bin/sh -c git clone ${LNDK_SOURCE} .     && git reset --hard ${LNDK_REF}     && cargo build --release]: exit code: 128`

I tested by moving to another dir, manually git cloning orbitalturtle/lndk, and reseting to that commit. Same error message about "couldn't parse object". It looks like the commit is missing?

### Context

Can't run the playground

### Expected Behavior

Expected the playground to be be accessible in a docker environment

### Steps to reproduce

See description ^^^

### Possible Solution

Switch to another commit in @orbitalturtle's repo?

**Comment by mrfelton** [comment]
Thanks for flagging. We're actively working on a number of updated to LNDK, and the PR that the commit that this project was incorporating was just rebased, hence why the commit no longer exists. Should be fixed in master now, through update in https://github.com/LN-Zap/bolt12-playground/pull/33.

**Comment by sbddesign** [comment]
That fixed it, thank you!
