### ISSUE TITLE
Init script errors

### ISSUE THREAD

**Issue by orbitalturtle** [LN-Zap/bolt12-playground#5]
### Bug Description

After running the docker compose commands, I get the the following errors when running `./scripts/init.sh`:

```./scripts/init.sh: 3: Bad substitution
./scripts/init.sh: 85: Syntax error: "(" unexpected (expecting "}")
```

I'm running on Ubuntu 22.04.4 LTS.

Thanks!

**Comment by mrfelton** [comment]
This looks like a shell specific error - what shell are you using?

**Comment by orbitalturtle** [comment]
Bash - default on Ubuntu

**Comment by mrfelton** [comment]
Could you share the logs from the init script please?

Could you also share the output of `/usr/bin/env sh --version`, thanks

**Comment by orbitalturtle** [comment]
The only output I get when running the script is:

    ./scripts/init.sh: 3: Bad substitution
    ./scripts/init.sh: 85: Syntax error: "(" unexpected (expecting "}")

When I run `/usr/bin/env sh --version` I get `sh: 0: Illegal option --`

Not sure if it helps, but if I run `bash --version` I get

    GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
    Copyright (C) 2020 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by mrfelton** [comment]
Could you try with the commit from https://github.com/LN-Zap/bolt12-playground/pull/6 please. I think it's because there is a hard dependency on bash in some of the shell scripts, but your environment doesn't look to be setup in a way in which bash is being used by these scripts.

**Comment by orbitalturtle** [comment]
Thanks! Indeed that gets the script running for me. :)

Though now when I run it I see the following:
```
Error response from daemon: No such container: bolt12-playground-bitcoind-1
Error response from daemon: No such container: bolt12-playground-bitcoind-1
Error response from daemon: No such container: bolt12-playground-bitcoind-1
bitcoind getnetworkinfo unavailable - waiting...
Error response from daemon: No such container: bolt12-playground-bitcoind-1
bitcoind getnetworkinfo unavailable - waiting...
```

Before that I had done `docker compose up` which gave me the following output:

```
[+] Running 1/7
 ⠹ bitcoind [⣿⠀⠀⠀⠀] Pulling                                                                                                                      2.1s 
   ✔ 4abcf2066143 Already exists                                                                                                                 0.0s 
   ⠦ 80856e167173 Pulling fs layer                                                                                                               0.6s 
   ⠦ c88aa88b47b7 Pulling fs layer                                                                                                               0.6s 
   ⠦ abb6906db016 Pulling fs layer                                                                                                               0.6s 
   ⠦ 71d547f6a94f Waiting                                                                                                                        0.6s 
 ⠹ cln1 Pulling                                                                                                                                  2.1s 
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by mrfelton** [comment]
That should be fixed in master with the merge of https://github.com/LN-Zap/bolt12-playground/pull/7.

**Comment by orbitalturtle** [comment]
Works perfectly for me, thanks! I'll close this out.
